site/conf/urls.py
from django.conf.urls import patterns, include, url
import socketio.sdjango


socketio.sdjango.autodiscover()


djagon_urlpatterns = patterns(
    '',
    url(r'^', include('home.urls')),
    url(r'^game/', include('ws_uno.urls')),
)

urlpatterns = patterns(
    '',
    url('^socket\.io', include(socketio.sdjango.urls)),
    url('^', include(djagon_urlpatterns, namespace='djagon')),
)

site/source/game/urls.py
from django.conf.urls import patterns, url
from source.game.views import create_game, play_game, join_random


urlpatterns = patterns('',
    url(r'^create/$', create_game, name='game-create'),
    url(r'^random/$', join_random, name='game-random'),
    url(r'^(?P<game_id>[A-F0-9]{6})/$', play_game, name='game-play'),
)

site/source/home/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'home.views',
    url(r'^$', 'home_page', name='home'),
)

site/source/ws_uno/urls.py
from django.conf.urls import patterns, url
from source.ws_uno.views import create_game, play_game, join_random

urlpatterns = patterns(
    '',
    url(r'^create/$', create_game, name='game-create'),
    url(r'^random/$', join_random, name='game-random'),
    url(r'^(?P<game_id>[A-F0-9]{6})/$', play_game, name='game-play'),
)

site/source/game/views.py
from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.views.generic.base import RedirectView, TemplateView
from source.game.models import GameTable
from source.game.game import Game


class CreateGameView(RedirectView):
    permanent = False

    def get_redirect_url(self, **kwargs):
        game = Game()
        game.save()
        return reverse('djagon:game-play', args=(game.game_id,))

create_game = CreateGameView.as_view()


class PlayGameView(TemplateView):
    template_name = 'game/game_page.html'

    def get_context_data(self, **kwargs):
        data = super(PlayGameView, self).get_context_data(**kwargs)
        data['game_id'] = self.kwargs.get('game_id')
        data['game_url'] = settings.GAME_SOCKET_URL
        return data

    def get(self, request, *args, **kwargs):
        game_id = self.kwargs.get('game_id')
        sessid = request.COOKIES.get('sessid')
        try:
            game = GameTable.objects.get(game_id=game_id)
        except GameTable.DoesNotExist:
            messages.warning(request, "There is no such game. Create yours!")
            return HttpResponseRedirect(reverse('djagon:home'))
        if game.players_number >= Game.PLAYERS_LIMIT:
            messages.warning(request, "Players number is limited in this game. Please, create yours!")
            return HttpResponseRedirect(reverse('djagon:home'))
        if game.status == game.STATUS_ACTIVE:
            if not sessid or not game.resolve().user_is_member(sessid):
                messages.warning(request, "This game has already been started")
                return HttpResponseRedirect(reverse('djagon:home'))
        elif not game.status in [game.STATUS_OPEN, game.STATUS_IDLE]:
            messages.warning(request, "This game has already been started")
            return HttpResponseRedirect(reverse('djagon:home'))

        return super(PlayGameView, self).get(self, request, *args, **kwargs)

play_game = PlayGameView.as_view()


class JoinRandomGameView(RedirectView):
    permanent = False

    def get_redirect_url(self, **kwargs):
        try:
            game = GameTable.objects.filter(status=GameTable.STATUS_OPEN, players_number__lt=Game.PLAYERS_LIMIT).order_by('?')[0]
            return reverse('djagon:game-play', args=(game.game_id,))
        except IndexError:
            messages.warning(self.request, "There are no open games. Create yours!")
            return reverse('djagon:home')

join_random = JoinRandomGameView.as_view()

site/source/home/views.py
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):
    template_name = 'home/home_page.html'

    def get_context_data(self, **kwargs):
        data = super(HomePageView, self).get_context_data(**kwargs)
        return data


home_page = HomePageView.as_view()

site/source/ws_uno/views.py
from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.views.generic.base import RedirectView, TemplateView
from source.storage.exceptions import GameDoesNotExist, NoOpenedGames, PlayerDoesNotExist
from source.storage.models import StoredGame
from source.storage import utils
from source.uno.game import Game


class CreateGameView(RedirectView):
    permanent = False

    def get_redirect_url(self, **kwargs):
        game = utils.create_new_game("new_game")
        return reverse('djagon:game-play', args=(game.game_id,))


create_game = CreateGameView.as_view()


class PlayGameView(TemplateView):
    template_name = 'game/game_page.html'

    def get_context_data(self, **kwargs):
        data = super(PlayGameView, self).get_context_data(**kwargs)
        data['game_id'] = self.kwargs.get('game_id')
        data['game_url'] = settings.GAME_SOCKET_URL
        return data

    def get(self, request, *args, **kwargs):
        game_id = self.kwargs.get('game_id')
        sessid = request.COOKIES.get('sessid')

        try:
            game, game_state = utils.fetch_game(game_id=game_id)
        except GameDoesNotExist:
            messages.warning(request, "There is no such game. Create yours!")
            return HttpResponseRedirect(reverse('djagon:home'))

        if len(game.players) == Game.PLAYERS_LIMIT:
            messages.warning(request, "Players number is limited in this game. Please, create yours!")
            return HttpResponseRedirect(reverse('djagon:home'))

        player = None
        if sessid:
            try:
                player = game.find_player_by_session_id(sessid)
            except PlayerDoesNotExist as e:
                pass

        if game_state == StoredGame.STATE_ACTIVE:
            if not player:
                messages.warning(request, "This game has already been started")
                return HttpResponseRedirect(reverse('djagon:home'))
        elif not game_state in [StoredGame.STATE_OPEN, StoredGame.STATE_IDLE]:
            messages.warning(request, "This game has already been started")
            return HttpResponseRedirect(reverse('djagon:home'))

        utils.save_game(game, StoredGame.STATE_OPEN)

        return super(PlayGameView, self).get(self, request, *args, **kwargs)


play_game = PlayGameView.as_view()


class JoinRandomGameView(RedirectView):
    permanent = False

    def get_redirect_url(self, **kwargs):
        try:
            game, state = utils.fetch_any_game()
            return reverse('djagon:game-play', args=(game.game_id,))
        except NoOpenedGames:
            messages.warning(self.request, "There are no open games. Create yours!")
            return reverse('djagon:home')


join_random = JoinRandomGameView.as_view()

site/source/common/templates/common/base.html
{% load static %}
{% load i18n %}
{% load compress %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Djagon - UNO with flavor of madness!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="DjangoDash 2013 participant"/>
    <link rel="shortcut icon" href="{% static 'common/img/favicon.ico' %}"/>

    <!-- Common styles bundle -->
    {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'common/css/base.scss' %}"/>
    {% endcompress %}

    <!-- Common scripts bundle -->
    {% compress js %}
    <script src="{% static 'common/libs/jquery/jquery.js' %}"></script>
    <script src="{% static 'common/libs/jquery/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'common/libs/noty/jquery.noty.js' %}"></script>
    <script type="text/javascript" src="{% static 'common/libs/noty/layouts/top.js' %}"></script>
    <script type="text/javascript" src="{% static 'common/libs/noty/layouts/topLeft.js' %}"></script>
    <script type="text/javascript" src="{% static 'common/libs/noty/layouts/topCenter.js' %}"></script>
    <script type="text/javascript" src="{% static 'common/libs/noty/themes/default.js' %}"></script>
    <script type="text/javascript" src="{% static 'common/libs/d3/d3.js' %}"></script>
    <script type="text/javascript" src="{% static 'common/js/messages.js' %}"></script>
    {% endcompress %}

    <!-- Custom static bundle -->
    {% block static %}
    {% endblock %}
</head>
<body>

<div class="page-container">
    {% include 'common/messages.html' %}

    {% block header %}
    {% include 'common/header.html' %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% include 'common/footer.html' %}
    {% endblock %}
</div>

</body>
</html>

site/source/common/templates/common/footer.html
<footer class="page-footer">
    <div class="copyrights">
        © {% now 'Y' %} All rights reserved. UNO® is a registered trademark of Mattel. This site is not affiliated with
        Mattel.
    </div>
    <div class="made-by">
        Made special for DjangoDash 2013 by <a href="http://webriders.com.ua/">WebRiders</a>
    </div>
</footer>

site/source/common/templates/common/header.html
<header class="page-header">
    <h1 class="title"><a href="/">Djagon</a></h1>

    <div class="slogan">
        UNO with flavor of madness!
    </div>
</header>

site/source/common/templates/common/messages.html
{% if messages %}
<script type="text/javascript">
    {% for message in messages %}
        {% with message|escapejs as message_text %}
            {% if 'success' in message.tags %}
                djagon.messages.success("{{ message_text }}");
            {% elif 'error' in message.tags %}
                djagon.messages.error("{{ message_text }}");
            {% elif 'info' in message.tags %}
                djagon.messages.info("{{ message_text }}");
            {% elif 'warning' in message.tags %}
                djagon.messages.warning("{{ message_text }}");
            {% else %}
                djagon.messages.alert("{{ message_text }}");
            {% endif %}
        {% endwith %}
    {% endfor %}
</script>
{% endif %}

site/source/home/templates/home/home_page.html
{% extends 'common/base.html' %}

{% load static %}
{% load compress %}

{% block static %}
{{ block.super }}

{% compress css %}
<link rel="stylesheet" type="text/x-scss" href="{% static 'home/css/home_page.scss' %}"/>
{% endcompress %}

{% compress js %}
<script type="text/javascript">
    $.noty.defaults.layout = 'topLeft';
</script>
{% endcompress %}
{% endblock %}

{% block header %}{# No default header on the Homepage #}{% endblock %}

{% block content %}
<aside class="intro">
    <h3 class="title">What is Djagon?</h3>

    <p>Djagon is browser-based multiplayer for
        <a href="http://shop.mattel.com/family/index.jsp?categoryId=3784337" target="_blank">Uno</a> -
        famous card game from Mattel.
    </p>

    <p>But why we say that it has flavor of madness?</p>

    <p>
        Because we play it by our own <a href="#"
                                         onclick="alert('Sorry, but we had no time to write them :('); return false;">crazy
        rules</a>
        (don't worry, just a few differences).
    </p>

    <p>
        <strong>We had too few time to implement all that we wanted. Excuse us for lot of bugs in gameplay :)</strong>
    </p>
</aside>

<div class="cards">
    <div class="one"></div>
    <div class="two"></div>
    <div class="three"></div>
</div>

<div class="actions">
    <a href="{% url 'djagon:game-create' %}" class="create-game">Create game</a>
    <a href="{% url 'djagon:game-random' %}" class="join-game">Join random game</a>
</div>
{% endblock %}

site/source/ws_uno/templates/game/game_page.html
{% extends 'common/base.html' %}

{% load static %}
{% load compress %}

{% block static %}
{{ block.super }}

{% compress css %}
<link rel="stylesheet" type="text/x-scss" href="{% static 'game/css/game.scss' %}"/>
<link rel="stylesheet" type="text/x-scss" href="{% static 'game/css/game_page.scss' %}"/>
{% endcompress %}

{% compress js %}
<script type="text/javascript" src="{% static 'common/libs/socket.io/socket.io.js' %}"></script>
<script type="text/javascript">WEB_SOCKET_SWF_LOCATION = '{% static 'common/libs/socket.io/WebSocketMain.swf' %}';</script>
<script type="text/javascript" src="{% static 'game/js/game.js' %}"></script>
<script type="text/javascript" src="{% static 'game/js/game_page.js' %}"></script>
{% endcompress %}
{% endblock %}

{% block content %}
<div class="game-table" id="game-table" data-game-id="{{ game_id }}" data-game-url="{{ game_url }}">
    <!-- Dynamic content -->
</div>
{% endblock %}